export const dummyProducts = [
  {
    id: "PROD-001",
    name: "Fresh Organic Avocados",
    mobileName: "Organic Avocados",
    shopName: "Green Pantry Organic",
    price: "$4.99",
    image:
      "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=150&h=150",
    category: "Grocery",
    mobileCategory: "GROCERY",
    distance: "0.8 km",
    mobileDistance: "0.8 km",
    rating: 4.9,
    reviews: "1.2k",
    status: "In Stock",
    isNew: true,
  },
  {
    id: "PROD-002",
    name: "Artisan Caramel Latte",
    mobileName: "Caramel Latte",
    shopName: "Urban Beans Coffee",
    price: "$5.50",
    image:
      "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=150&h=150",
    category: "Cafe",
    mobileCategory: "CAFE",
    distance: "1.2 km",
    mobileDistance: "1.2 km",
    rating: 4.7,
    reviews: "856",
    status: "In Stock",
    isNew: false,
  },
  {
    id: "PROD-003",
    name: "Noise-Cancelling Headphones",
    mobileName: "Wireless Headphones",
    shopName: "Tech Haven Hub",
    price: "$199.99",
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=150&h=150",
    category: "Electronics",
    mobileCategory: "ELECTRONICS",
    distance: "2.5 km",
    mobileDistance: "2.5 km",
    rating: 4.5,
    reviews: "430",
    status: "Low Stock",
    isNew: false,
  },
  {
    id: "PROD-004",
    name: "Adjustable Dumbbell Set",
    mobileName: "Dumbbell Set",
    shopName: "Apex Fitness Gear",
    price: "$89.00",
    image:
      "https://images.unsplash.com/photo-1638202993928-7267aad84c31?auto=format&fit=crop&w=150&h=150",
    category: "Fitness",
    mobileCategory: "FITNESS",
    distance: "3.1 km",
    mobileDistance: "3.1 km",
    rating: 4.8,
    reviews: "621",
    status: "In Stock",
    isNew: false,
  },
  {
    id: "PROD-005",
    name: "Whole Wheat Artisan Bread",
    mobileName: "Artisan Bread",
    shopName: "SkyMart Superstore",
    price: "$3.49",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=150&h=150",
    category: "Supermarket",
    mobileCategory: "SUPERMARKET",
    distance: "4.2 km",
    mobileDistance: "4.2 km",
    rating: 4.6,
    reviews: "2.1k",
    status: "In Stock",
    isNew: false,
  },
  {
    id: "PROD-006",
    name: "Premium Vitamin C 1000mg",
    mobileName: "Vitamin C",
    shopName: "Peak Pharmacy",
    price: "$12.99",
    image:
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=150&h=150",
    category: "Pharmacy",
    mobileCategory: "PHARMACY",
    distance: "1.5 km",
    mobileDistance: "1.5 km",
    rating: 4.9,
    reviews: "950",
    status: "In Stock",
    isNew: true,
  },
  {
    id: "PROD-007",
    name: "Gourmet Chocolate Truffle Cake",
    mobileName: "Chocolate Cake",
    shopName: "Bake & Cake",
    price: "$24.00",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=150&h=150",
    category: "Bakery",
    mobileCategory: "BAKERY",
    distance: "2.1 km",
    mobileDistance: "2.1 km",
    rating: 4.4,
    reviews: "320",
    status: "Out of Stock",
    isNew: false,
  },
  {
    id: "PROD-008",
    name: "Ergonomic Office Chair",
    mobileName: "Office Chair",
    shopName: "Home Goods Plus",
    price: "$145.00",
    image:
      "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=150&h=150",
    category: "Furniture",
    mobileCategory: "FURNITURE",
    distance: "5.0 km",
    mobileDistance: "5.0 km",
    rating: 4.3,
    reviews: "150",
    status: "In Stock",
    isNew: false,
  },
];
